apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-service
spec:
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
